### ISSUE TITLE
Compile error. Check my Screenshot

### ISSUE THREAD

**Issue by saianwork** [krijnsent/crypto_vba#1] opened 2017-10-10 15:30 UTC
![image](https://user-images.githubusercontent.com/31490998/31395266-aa13d8e2-ade0-11e7-8111-83c35c67d30e.png)

Can you make some steps on how to get started. It's really not clear please.

thanks for you work.

**Comment by krijnsent** [comment] 2017-10-17 11:29
Thanks for the feedback. I pushed a new version which should work. This error is probably caused by the way I update my example file, which should be correct now (manually checked it).

**Comment by krijnsent** [comment] 2017-10-17 13:51
Seems to work for saianwork, closing issue

**Closed by krijnsent** 2017-10-17 13:51 UTC
